# Generated by Django 5.0.4 on 2024-04-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='income',
        ),
    ]
